Repository julsgasull/FIB-PES-LAB, pull requests merged in 2020-04, with the labels that each got.

#38 Finished Swagger
  Sources/purplepoint-backend/pom.xml
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/config/OpenApiConfig.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/config/SwaggerConfig.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/controller/UserController.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/exception/UserNotFoundException.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/User.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/UserRepository.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/UserService.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/UserServiceImpl.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/security/AuthServer.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/security/JWTAuthorizationFilter.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/utils/DataLoader.java
  Sources/purplepoint-backend/src/main/resources/application.properties
  Sources/purplepoint-backend/src/test/java/com/pesados/purplepoint/api/tests/controller/UserControllerTest.java
Labels: documentation

#47 Removed unnecesary dependencies on poml.xml and cleansed swagger
  Sources/purplepoint-backend/pom.xml
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/image/Image.java
Labels: enhancement

#56 Register only allows unique emails now
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/controller/ImageController.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/controller/UserController.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/model/alarm/AlarmServiceImpl.java
  Sources/purplepoint-backend/src/main/java/com/pesados/purplepoint/api/utils/DataLoader.java
Labels: bug
